services:
  postgres:
    image: postgres:16-alpine
    container_name: employee-data-service-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: employees
      POSTGRES_USER: employees_app
      POSTGRES_PASSWORD: employees_app_password
    ports:
       - "5433:5432"
    volumes:
      - employee_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-employees_app} -d ${DB_NAME:-employees}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  employee_db_data: